export const LoaderConfig = {
  background: require("../sprites/background-mountains.png"),
  hinto: require("../sprites/hinto-2.png"),
  gem: require("../sprites/lemon.png"),
  platform: require("../sprites/platform.png"),
  tile: require("../sprites/tile.png"),
  c1: require("../sprites/c1.png"),
  c2: require("../sprites/c2.png"),
  c3: require("../sprites/c3.png"),
  c4: require("../sprites/c4.png"),
  c5: require("../sprites/c5.png"),
  c6: require("../sprites/c6.png"),
  c7: require("../sprites/c7.png"),
  c8: require("../sprites/c8.png"),
  music: require("../sounds/music.mp3"),
  crunch: require("../sounds/crunch.mp3"),
  coin: require("../sounds/coin.mp3"),
  scream: require("../sounds/scream.mp3"),
  hop: require("../sounds/hop.mp3"),
};
